Check dnsmasq after download.
Signed-off-by: kongfl888 K <kongfl888@outlook.com>

diff --git a/root/etc/init.d/dnsfilter b/root/etc/init.d/dnsfilter
--- a/root/etc/init.d/dnsfilter
+++ b/root/etc/init.d/dnsfilter
@@ -16,6 +16,7 @@ FWI=$(uci -q get firewall.dnsfilter.path)
 enable=$(uci -q get dnsfilter.@dnsfilter[0].enable)
 flash=$(uci -q get dnsfilter.@dnsfilter[0].flash)
 url=$(uci -q get dnsfilter.@dnsfilter[0].url)
+apptest=`uci -q get dnsfilter.@dnsfilter[0].app_test`
 
 get_config(){
 	config_get_bool cron_mode $1 cron_mode 1
@@ -382,6 +383,21 @@ del_rule(){
 	gen
 }
 
+rs_dnsmasq(){
+	/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	[ "$apptest" = "1" ] || return 0
+	sh $P/testdns
+	local R=$?
+	if [ $R == 1 ];then
+		echo "`eval $E` [DNS Check ERROR]"
+		echo "`eval $E` [DNS Check ERROR. Please check your rules or your system.]" >> $Logfile
+		rm -f $D/rules.conf
+		[ -f $L/rules/rules.conf ] && echo -n > $L/rules/rules.conf
+		[ -f $T/rules.conf ] && echo -n > $T/rules.conf
+		/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	fi
+}
+
 start(){
 	config_load dnsfilter
 	config_foreach get_config dnsfilter
@@ -409,7 +425,7 @@ start(){
 	add_cron
 	if [ $STATUS = Y ];then
 		echo "`eval $E` [Dnsmasq Change]"
-		/etc/init.d/dnsmasq restart >/dev/null 2>&1
+		rs_dnsmasq
 	fi
 }
 
@@ -429,7 +445,7 @@ stop(){
 	if [ $STATUS = Y ];then
 		rm -rf $T
 		echo "`eval $E` [Revert Dnsmasq]"
-		/etc/init.d/dnsmasq restart >/dev/null 2>&1
+		rs_dnsmasq
 		rm -f $Logfile
 	fi
 }
@@ -441,7 +457,7 @@ restart(){
 		stop
 		start
 		echo "`eval $E` [Restart Dnsmasq]"
-		/etc/init.d/dnsmasq restart >/dev/null 2>&1
+		rs_dnsmasq
 	else
 		stop
 	fi
diff --git a/root/usr/share/dnsfilter/adupdate b/root/usr/share/dnsfilter/adupdate
--- a/root/usr/share/dnsfilter/adupdate
+++ b/root/usr/share/dnsfilter/adupdate
@@ -2,8 +2,28 @@
 # [K]2022
 # https://github.com/kongfl888
 
+A=`uci -q get dnsfilter.@dnsfilter[0].app_test`
 C=/tmp/adupdate_dnsfilter.log
 D="date +'%Y-%m-%d %H:%M:%S'"
+E=/tmp/dnsmasq.dnsfilter
+P=/usr/share/dnsfilter
+T=/tmp/dnsfilter
+L=/etc/dnsfilter
+
+rs_dnsmasq(){
+	/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	[ "$A" = "1" ] || return 0
+	sh $P/testdns
+	local R=$?
+	if [ $R == 1 ];then
+		echo "`eval $D` [DNS Check ERROR]"
+		echo "`eval $D` [DNS Check ERROR. Please check your rules or your system.]" >> $C
+		rm -f $E/rules.conf
+		[ -f $L/rules/rules.conf ] && echo -n > $L/rules/rules.conf
+		[ -f $T/rules.conf ] && echo -n > $T/rules.conf
+		/etc/init.d/dnsmasq restart >/dev/null 2>&1
+	fi
+}
 
 echo "`eval $D` [Check Subscribe Rules Update]" >> $C
 
